name: Front-end Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # 1. Docker 이미지 빌드
      - name: Build Docker Image
        run: docker build -t feed1119/github-52panda-ci-test .

      # 2. DockerHub 로그인
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 3. Docker Hub 이미지 푸시
      - name: Push Docker Image to Docker Hub
        run: docker push feed1119/github-52panda-ci-test
