name: Front-end Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps: 
      # 1. Node.js 설치
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 2. 의존성 설치
      - name: Install dependencies
        run: yarn install 

      - name: Change working directory
        run: cd ${{ github.workspace }}

      # 3. 프론트엔드 애플리케이션 빌드
      - name: Build Frontend
        run: yarn build

      # 1. Docker 이미지 빌드
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/github-52panda-ci-test .

      # 2. DockerHub 로그인
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 3. Docker Hub 이미지 푸시
      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/github-52panda-ci-test
