name: Front-end Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # 1. Node.js 및 yarn 설치
    - name: Install Node.js and yarn
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'yarn'

    # 2. 의존성 설치
    - name: Install dependencies
      run: yarn install

    # 3. React 애플리케이션 빌드
    - name: Build React App
      run: yarn build

    # 4. Docker 이미지 빌드
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo .

    # 5. DockerHub 로그인
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # 6. Docker Hub 이미지 푸시
    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo
